receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318  # OpenTelemetry recebe apenas traces via HTTP

exporters:
  otlphttp:
    endpoint: "http://tempo:4321"  # Exporta traces para Grafana Tempo

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]  # Apenas exportação de traces
