global:
    scrape_interval: 2s
    evaluation_interval: 2s


scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: 
            - prometheus:9090
    - job_name: 'spring-config-server'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: 
          - spring-config-server
 