global:
  resolve_timeout: 5m

route:
  receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
      - to: 'seu-email@dominio.com'
        from: 'alertmanager@dominio.com'
        smarthost: 'smtp.dominio.com:587'
        auth_username: 'usuario_smtp'
        auth_password: 'senha_smtp'
