global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/rules/*.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - prometheus:9090

  - job_name: 'spring-config-server'
    metrics_path: '/infra/config/actuator/prometheus'
    static_configs:
      - targets: 
        - spring-config-server:8888
        labels:
          application: 'spring-config-server'
  
  - job_name: 'spring-api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - spring-api-gateway:9999
        labels:
          application: 'spring-api-gateway'

  - job_name: 'spring-user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - spring-user:8091
        labels:
          application: 'spring-user'
  
  - job_name: 'spring-event-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - spring-event-service:8092
        labels:
          application: 'spring-event-service'